#!/bin/bash
ARGS="0,10,26-28,33-40,43,58-61"
while read p; do
a= echo $p | cut -d "," -f 1
b= echo $p | cut -d "," -f 2
#$a = echo $a | xargs
#$b = echo $b | xargs
echo cwevent -f $ARGS -y $a $b
done <teams.txt